export const translatedCategories: Record<string, string> = {
    '飛竜種': 'Wyvern Voador',
    '古龍種': 'Dragão Ancião',
    '牙獣種': 'Besta de Presas',
    '海竜種': 'Wyvern Aquático',
    '獣竜種': 'Wyvern Bruto',
    '魚竜種': 'Wyvern Piscino',
    '鳥竜種': 'Wyvern Pássaro',
    '牙竜種': 'Wyvern de Presas',
    '鋏角種': 'Temnocera (Aracnídeo)',
    '両生種': 'Anfíbio',
    '蛇竜種': 'Snake Wyvern',
    '甲虫種': 'Neopteron (Inseto)',
    '甲殻種': 'Carapaceon (Crustáceo)'
};
export const translatedTitles: Record<string, string> = {
    'MH': 'Monster Hunter',
    'MHG': 'Monster Hunter G',
    'MHP': 'MH Freedom',
    'MH2': 'Monster Hunter 2',
    'P2nd': 'MH Freedom 2',
    'P2G': 'MH Freedom Unite',
    'MH3': 'Monster Hunter 3',
    'MHP3rd': 'MH Portable 3rd',
    '3G': 'Monster Hunter 3 Ultimate',
    'MH3G': 'Monster Hunter 3 Ultimate',
    'MH4': 'Monster Hunter 4',
    '4G': 'Monster Hunter 4 Ultimate',
    'MH4G': 'Monster Hunter 4 Ultimate',
    'MHX': 'Monster Hunter Generations',
    'XX': 'MH Generations Ultimate',
    'MHXX': 'MH Generations Ultimate',
    'MHW': 'Monster Hunter: World',
    'IB': 'MH World: Iceborne',
    'MHWI': 'MH World: Iceborne',
    'MHR': 'Monster Hunter Rise',
    'SB': 'MH Rise: Sunbreak',
    'MHRS': 'MH Rise: Sunbreak',
    'MHF': 'Monster Hunter Frontier'
};
export const translatedMonsters: Record<string, { nome: string; apelido: string }> = {
    'ドスガレオス': { nome: 'Cephadrome', apelido: 'Líder dos Cephalos' },
    '傀異克服 クシャルダオラ': { nome: 'Kushala Daora Erguido (Risen)', apelido: 'Dragão de Aço' },
    'イャンクック': { nome: 'Yian Kut-Ku', apelido: 'Ave Estranha' },
    'イャンクック亜種': { nome: 'Yian Kut-Ku Azul', apelido: 'Ave Estranha Azul' },
    'ゲリョス': { nome: 'Gypceros', apelido: 'Ave Venenosa Estranha' },
    'ゲリョス亜種': { nome: 'Gypceros Roxo', apelido: 'Ave Venenosa Estranha' },
    'ガノトトス': { nome: 'Plesioth', apelido: 'Wyvern Aquático' },
    'ガノトトス亜種': { nome: 'Plesioth Verde', apelido: 'Wyvern Aquático Verde-Esmeralda' },
    '黒龍 ミラボレアス': { nome: 'Fatalis Negro', apelido: 'Dragão Negro' },
    '紅龍 ミラボレアス': { nome: 'Fatalis Carmesim', apelido: 'Dragão Carmesim' },
    '祖龍 ミラボレアス': { nome: 'Fatalis Branco', apelido: 'Dragão Ancestral' },
    'ドスランポス': { nome: 'Velocidrome', apelido: 'Líder dos Velociprey' },
    'ドスゲネポス': { nome: 'Gendrome', apelido: 'Líder dos Genprey' },
    'ドスイーオス': { nome: 'Iodrome', apelido: 'Líder dos Ioprey' },
    'イャンガルルガ': { nome: 'Yian Garuga', apelido: 'Lobo Solitário Pássaro' },
    '隻眼イャンガルルガ': { nome: 'Yian Garuga Caolho', apelido: 'Lobo Solitário Pássaro De Um Olho' },
    '傷ついた イャンガルルガ': { nome: 'Yian Garuga Sifão', apelido: 'Lobo Solitário Pássaro Ferido' },
    'ダイミョウザザミ': { nome: 'Daimyo Hermitaur', apelido: 'Caranguejo Escudo' },
    'ダイミョウザザミ 亜種': { nome: 'Daimyo Hermitaur Ameixa', apelido: 'Caranguejo Escudo Roxo' },
    '矛砕 ダイミョウザザミ': { nome: 'Daimyo Hermitaur Rompe-Lança', apelido: 'Caranguejo Escudo Guardião' },
    'ショウグンギザミ': { nome: 'Shogun Ceanataur', apelido: 'General Foice' },
    'ショウグンギザミ 亜種': { nome: 'Shogun Ceanataur Terra', apelido: 'General Foice da Terra' },
    '鎧裂 ショウグンギザミ': { nome: 'Shogun Ceanataur Quebra-Armadura', apelido: 'General Foice de Armadura' },
    'ババコンガ': { nome: 'Congalala', apelido: 'Besta de Pelagem Rosa' },
    'ババコンガ亜種': { nome: 'Congalala Esmeralda', apelido: 'Besta de Pelagem Verde' },
    'ドドブランゴ': { nome: 'Blangonga', apelido: 'Líder dos Leões da Neve' },
    'ドドブランゴ亜種': { nome: 'Blangonga de Cobre', apelido: 'Líder dos Leões da Areia' },
    '傀異克服オオナズチ': { nome: 'Chameleos Erguido (Risen)', apelido: 'Dragão de Névoa Superado' },
    '傀異克服 テオ・テスカトル': { nome: 'Teostra Erguido (Risen)', apelido: 'Rei do Fogo Superado' },
    'ドスファンゴ': { nome: 'Bulldrome', apelido: 'Grande Javali' },
    'キングチャチャブー': { nome: 'King Shakalaka', apelido: 'Rei Máscara Bizarra' },
    'ティガレックス 希少種': { nome: 'Tigrex Mutante', apelido: 'Grande Wyvern Rugidor' },
    '荒鉤爪 ティガレックス': { nome: 'Tigrex Garra Atroz', apelido: 'Wyvern Rugidor das Garras Ásperas' },
    'ドスギアノス': { nome: 'Giadrome', apelido: 'Líder dos Giaprey' },
    'ヒプノック': { nome: 'Hypnocatrice', apelido: 'Ave do Sono' },
    'ヴォルガノス': { nome: 'Lavasioth', apelido: 'Wyvern de Lava' },
    'クイーンランゴスタ': { nome: 'Vespoid Queen', apelido: 'Inseto Rainha' },
    'クルペッコ': { nome: 'Qurupeco', apelido: 'Ave Colorida' },
    'クルペッコ亜種': { nome: 'Qurupeco Carmesim', apelido: 'Ave Colorida Vermelha' },
    'ギギネブラ': { nome: 'Gigginox', apelido: 'Wyvern Sanguessuga Venenoso' },
    'ギギネブラ亜種': { nome: 'Gigginox Elétrico', apelido: 'Wyvern Sanguessuga Trovão' },
    'ベリオロス': { nome: 'Barioth', apelido: 'Wyvern de Presas de Gelo' },
    'ベリオロス亜種': { nome: 'Barioth de Areia', apelido: 'Wyvern de Presas do Vento' },
    '氷刃佩くベリオロス': { nome: 'Barioth Presa-Gélida', apelido: 'Wyvern de Presas de Gelo' },
    '怒り喰らう イビルジョー': { nome: 'Savage Deviljho', apelido: 'Wyvern Tirano Faminto' },
    'ボルボロス': { nome: 'Barroth', apelido: 'Wyvern de Lama' },
    'ボルボロス亜種': { nome: 'Barroth de Jade', apelido: 'Wyvern Quebra-Gelo' },
    'ウラガンキン': { nome: 'Uragaan', apelido: 'Wyvern do Martelo Explosivo' },
    'ウラガンキン亜種': { nome: 'Uragaan de Aço', apelido: 'Wyvern do Martelo de Aço' },
    '宝纏ウラガンキン': { nome: 'Uragaan Joia-Preciosa', apelido: 'Wyvern do Martelo Cristalino' },
    'ロアルドロス': { nome: 'Royal Ludroth', apelido: 'Besta Esponja Real' },
    'ロアルドロス亜種': { nome: 'Royal Ludroth Roxo', apelido: 'Besta Esponja Roxa' },
    'チャナガブル': { nome: 'Gobul', apelido: 'Peixe-Lanterna Wyvern' },
    'リオレイア': { nome: 'Rathian', apelido: 'Dragão Fêmea Terrestre' },
    'リオレイア亜種': { nome: 'Rathian Rosa', apelido: 'Wyvern de Cerejeira' },
    'リオレイア希少種': { nome: 'Rathian Dourada', apelido: 'Wyvern de Ouro' },
    '紫毒姫リオレイア': { nome: 'Rathian Rainha Dracônica', apelido: 'Princesa do Veneno Roxo' },
    'ヌシ・リオレイア': { nome: 'Rathian Apex', apelido: 'Líder Rathian' },
    'リオレウス': { nome: 'Rathalos', apelido: 'Rei dos Céus' },
    'リオレウス亜種': { nome: 'Rathalos Azul', apelido: 'Wyvern Azure' },
    'リオレウス希少種': { nome: 'Rathalos Prateado', apelido: 'Wyvern de Prata' },
    '黒炎王リオレウス': { nome: 'Rathalos Rei Maldito', apelido: 'Soberano das Chamas Negras' },
    'ヌシ・リオレウス': { nome: 'Rathalos Apex', apelido: 'Líder Rathalos' },
    'フルフル': { nome: 'Khezu', apelido: 'Wyvern Pálido' },
    'フルフル亜種': { nome: 'Khezu Vermelho', apelido: 'Wyvern Sangrento' },
    'バサルモス': { nome: 'Basarios', apelido: 'Wyvern de Pedra' },
    'バサルモス亜種': { nome: 'Basarios Rubro', apelido: 'Wyvern de Cristal' },
    'グラビモス': { nome: 'Gravios', apelido: 'Wyvern de Armadura' },
    'グラビモス亜種': { nome: 'Gravios Negro', apelido: 'Wyvern de Grafite' },
    'モノブロス': { nome: 'Monoblos', apelido: 'Wyvern de Um Chifre' },
    'モノブロス亜種': { nome: 'Monoblos Branco', apelido: 'Wyvern Alvo' },
    'ディアブロス': { nome: 'Diablos', apelido: 'Wyvern de Chifres' },
    'ディアブロス亜種': { nome: 'Diablos Negra', apelido: 'Wyvern Negra Temível' },
    '鏖魔ディアブロス': { nome: 'Diablos Massacre', apelido: 'Demônio do Chifre Quebrado' },
    'ヌシ・ディアブロス': { nome: 'Diablos Apex', apelido: 'Líder Diablos' },
    'ティガレックス': { nome: 'Tigrex', apelido: 'Wyvern Rugidor' },
    'ティガレックス亜種': { nome: 'Tigrex Negro', apelido: 'Wyvern Bruto' },
    '荒鉤爪ティガレックス': { nome: 'Tigrex Garra Atroz', apelido: 'Tigrex de Garras Ásperas' },
    'ナルガクルガ': { nome: 'Nargacuga', apelido: 'Wyvern Veloz' },
    'ナルガクルガ亜種': { nome: 'Nargacuga Verde', apelido: 'Wyvern Verdejante' },
    'ナルガクルガ希少種': { nome: 'Nargacuga Lucent', apelido: 'Wyvern Fantasma Lunático' },
    '白疾風ナルガクルガ': { nome: 'Nargacuga Vento Alvo', apelido: 'Vendaval Branco' },
    'ラギアクルス': { nome: 'Lagiacrus', apelido: 'Senhor dos Mares' },
    'ラギアクルス亜種': { nome: 'Lagiacrus Marfim', apelido: 'Wyvern Relâmpago Branco' },
    'ラギアクルス希少種': { nome: 'Lagiacrus Abissal', apelido: 'Wyvern do Abismo Escuro' },
    'ジンオウガ': { nome: 'Zinogre', apelido: 'Lobo Relâmpago' },
    'ジンオウガ亜種': { nome: 'Zinogre Estígio', apelido: 'Lobo das Chamas Negras' },
    '金雷公ジンオウガ': { nome: 'Zinogre Lorde Relâmpago', apelido: 'Soberano do Trovão Dourado' },
    'ヌシ・ジンオウガ': { nome: 'Zinogre Apex', apelido: 'Líder Zinogre' },
    'ブラキディオス': { nome: 'Brachydios', apelido: 'Wyvern de Britagem' },
    '砕光のブラキディオス': { nome: 'Brachydios Crítico', apelido: 'Punho Explosivo Atômico' },
    'ゴア・マガラ': { nome: 'Gore Magala', apelido: 'Dragão Sombrio Blindado' },
    '混沌に呻くゴア・マガラ': { nome: 'Gore Magala Caótico', apelido: 'Aquele que Geme no Caos' },
    'セルレギオス': { nome: 'Seregios', apelido: 'Wyvern de Mil Lâminas' },
    'ディノバルド': { nome: 'Glavenus', apelido: 'Wyvern de Lâmina Cortante' },
    'ディノバルド亜種': { nome: 'Glavenus Ácido', apelido: 'Wyvern de Lâmina de Enxofre' },
    '斬竜ディノバルド': { nome: 'Glavenus', apelido: 'Wyvern de Lâmina Cortante' },
    'ライゼクス': { nome: 'Astalos', apelido: 'Wyvern de Eletricidade' },
    'タマミツネ': { nome: 'Mizutsune', apelido: 'Dragão de Bolhas' },
    '天眼タマミツネ': { nome: 'Mizutsune Olho Celestial', apelido: 'Raposa de Bolhas Cega' },
    'ヌシ・タマミツネ': { nome: 'Mizutsune Apex', apelido: 'Líder Mizutsune' },
    'ガムート': { nome: 'Gammoth', apelido: 'Besta Gigante da Neve' },
    'バルファルク': { nome: 'Valstrax', apelido: 'Dragão Cometa' },
    '奇しき赫耀のバルファルク': { nome: 'Valstrax Brilho Carmesim', apelido: 'Estrela Vermelha do Desespero' },
    'ネルギガンテ': { nome: 'Nergigante', apelido: 'Dragão da Extinção' },
    '悉くを殲ぼすネルギガンテ': { nome: 'Nergigante Ruiner', apelido: 'Aniquilador Absoluto' },
    'イヴェルカーナ': { nome: 'Velkhana', apelido: 'Dragão de Gelo Cristalino' },
    'マガイマガド': { nome: 'Magnamalo', apelido: 'Wyvern de Rancor' },
    '怨嗟響めくマガイマガド': { nome: 'Magnamalo Desprezível', apelido: 'Malícia Ecoante' },
    'メル・ゼナ': { nome: 'Malzeno', apelido: 'Dragão Vampiro Real' },
    '原初を刻むメル・ゼナ': { nome: 'Malzeno Primordial', apelido: 'Aquele que Entalha o Início' },
    'キリン': { nome: 'Kirin', apelido: 'Besta Fantasma do Trovão' },
    'キリン亜種': { nome: 'Kirin Gelo', apelido: 'Besta Fantasma Negra' },
    'クシャルダオラ': { nome: 'Kushala Daora', apelido: 'Dragão de Vento de Aço' },
    '錆びたクシャルダオラ': { nome: 'Kushala Daora Enferrujado', apelido: 'Dragão de Metal Oxidado' },
    'オオナズチ': { nome: 'Chameleos', apelido: 'Dragão de Névoa' },
    '霞龍オオナズチ': { nome: 'Chameleos', apelido: 'Dragão de Névoa' },
    'テオ・テスカトル': { nome: 'Teostra', apelido: 'Imperador das Chamas' },
    'ナナ・テスカトリ': { nome: 'Lunastra', apelido: 'Imperatriz das Chamas' },
    'ラオシャンロン': { nome: 'Lao-Shan Lung', apelido: 'Dragão de Montanha Antigo' },
    'ラオシャンロン亜種': { nome: 'Lao-Shan Lung Ashen', apelido: 'Dragão Cinzento' },
    'シェンガオレン': { nome: 'Shen Gaoren', apelido: 'Caranguejo da Fortaleza' },
    'ヤマツカミ': { nome: 'Yama Tsukami', apelido: 'Dragão Flutuante de Madeira' },
    'ジエン・モーラン': { nome: 'Jhen Mohran', apelido: 'Dragão de Areia Gigante' },
    'ジエン・モーラン亜種': { nome: 'Jhen Mohran Hallowed', apelido: 'Dragão de Cristal Ametista' },
    'ダレン・モーラン': { nome: 'Dah\'ren Mohran', apelido: 'Dragão Broca da Areia' },
    'アマツマガツチ': { nome: 'Amatsu', apelido: 'Tempestade Celestial' },
    '嵐龍アマツマガツチ': { nome: 'Amatsu', apelido: 'Tempestade Celestial' },
    'ダラ・アマデュラ': { nome: 'Dalamadur', apelido: 'Serpente Gigante do Ecossistema' },
    'オストガロア': { nome: 'Nakarkos', apelido: 'Dragão de Ossos do Abismo' },
    'アトラル・カ': { nome: 'Ahtal-Ka', apelido: 'Gafanhoto Trono Imperial' },
    'ゾラ・マグダラオス': { nome: 'Zorah Magdaros', apelido: 'Dragão Montanha de Magma' },
    'ゼノ・ジーヴァ': { nome: 'Xeno\'jiiva', apelido: 'Dragão Negro Imperador' },
    'アン・イシュワルダ': { nome: 'Shara Ishvalda', apelido: 'Dragão da Origem da Terra' },
    'ムフェト・ジーヴァ': { nome: 'Safi\'jiiva', apelido: 'Dragão Vermelho Imperador' },
    'イブシマキヒコ': { nome: 'Ibushi', apelido: 'Serpente do Vento Cósmico' },
    '百竜ノ淵源ナルハタタヒメ': { nome: 'Narwa Allmother', apelido: 'Origem do Relâmpago Ancestral' },
    'ガイアデルム': { nome: 'Gaismagorm', apelido: 'Demônio do Abismo do Inferno' },
    'イビルジョー': { nome: 'Deviljho', apelido: 'Wyvern Voraz' },
    'ラージャン': { nome: 'Rajang', apelido: 'Besta Dourada Furiosa' },
    '激昂したラージャン': { nome: 'Furious Rajang', apelido: 'Fúria de Ouro Eterna' },
    'バザルギウス': { nome: 'Bazelgeuse', apelido: 'Wyvern de Bombardeio' },
    '紅蓮滾るバゼルギウス': { nome: 'Seething Bazelgeuse', apelido: 'Chamas de Bombardeio Crítico' },
    'アカムトルム': { nome: 'Akantor', apelido: 'Deus Negro da Fornalha' },
    'ウカムルバス': { nome: 'Ukanlos', apelido: 'Deus Branco da Neve' },
    'アルバトリオン': { nome: 'Alatreon', apelido: 'Dragão Negro Reluzente' },
    'グラン・ミラオス': { nome: 'Dire Miralis', apelido: 'Dragão da Destruição Escarlate' },
    'ミラボレアス': { nome: 'Fatalis', apelido: 'Dragão Negro Lendário' },
    'ミラバルカン': { nome: 'Fatalis Carmesim', apelido: 'Fúria Escarlate Lendária' },
    'ミラルーツ': { nome: 'Fatalis Branco', apelido: 'Ancestral de Todos os Dragões' }
};
export function traduzirInfo(japanese: string) {
    const monster = translatedMonsters[japanese];
    if (monster) return monster;
    return { nome: japanese, apelido: 'Registro da Guilda' };
}